title: Anti-Transphobia Library
description: A resource for debunking and combating transphobia online.
theme: just-the-docs

url: https://bethylamine.github.io

aux_links:
  Template Repository: https://github.com/bethylamine/bethylamine.github.io

nav_external_links:
  - title: Beth on Twitter
  - url: https://twitter.com/bethylamine
